# PHP CircleCI 2.0 configuration file
#
version: 2
jobs:
  wospm-checker:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.2
    steps:
      - checkout
      - run: 
          name: WOSPM-Checker
          no_output_timeout: 20m
          command: mkdir /tmp/tool && cd /tmp/tool && composer require --dev wospm/checker && cd - && /tmp/tool/wospm-checker
  doc-lint:
    docker:
      - image: circleci/node:9.8
    steps:
      - checkout
      - run:
          name: Project-Markdown-Lint
          no_output_timeout: 20m
          command: sudo npm install -g markdownlint-cli && markdownlint *.md CODE_OF_CONDUCT
workflows:
  version: 2
  build_and_create:
    jobs:
      - wospm-checker
      - doc-lint
